version: '2'
services:

  mysql:
    image: mysql:8
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: wardrobe_test
      MYSQL_USER: test_dev
      MYSQL_PASSWORD: longpassword
    ports:
      - 3307:3306
    security_opt:
      - seccomp:unconfined

  jm-api-service:
    image: api-service
    ports:
    - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wardrobe_test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
    - mysql

  jm-parser:
    image: parser
    ports:
      - 8070:8070
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wardrobe_test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysql