version: '2'
services:

  mysql-docker-container:
    image: mysql:8
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: wardrobe_test
      MYSQL_USER: test_dev
      MYSQL_PASSWORD: longpassword
    ports:
      - 3307:3306
    security_opt:
      - seccomp:unconfined

  jm-api-service:
    image: api-service
    command: ["./wait-for-it.sh", "mysql-docker-container:3306", "--", "java", "-jar", "api-service.jar"]
    ports:
    - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/wardrobe_test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
    - mysql-docker-container

  jm-parser:
    image: parser
    command: ["./wait-for-it.sh", "mysql-docker-container:3306", "--", "java", "-jar", "parser.jar"]
    ports:
      - 8070:8070
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/wardrobe_test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysql-docker-container